### ISSUE TITLE
【功能建议】图片拼接和自动边框裁剪

### ISSUE THREAD

**Issue by 775405984** [CNOliverZhang/PotatofieldImageToolkit#1]
1.现在软件有个长图拼接工具，但是我主要用的其实是“宽图”拼接，就是图片横向拼接。

2.自动边框裁剪: 可以裁剪掉黑边、白边、蕾丝边之类的边框。

谢谢！

**Comment by CNOliverZhang** [comment]
谢谢建议！横向拼接功能我会尽快实现，请关注近期的版本更新。自动边框裁切实现的技术成本较高，目前所选用的技术栈基本无法实现，所以暂时不考虑添加自动裁切功能。
