### ISSUE TITLE
1.5.0版本窗口变小

### ISSUE THREAD

**Issue by l-g-w** [CNOliverZhang/PotatofieldImageToolkit#10]
作者你好：
我将1.3.0老版本卸载后，去官网下载了1.5.0的安装包手动安装，打开后窗口和字相较于之前变小了，使用富文本等选项多的工具时很费眼睛，如下图：
主界面：https://img04.sogoucdn.com/app/a/100520146/f145c109970aded2838e656447516d27
富文本：https://s2.ax1x.com/2020/02/22/3KxJr4.png
我的显示器分辨率为：1366*768
此前1.3.0版本的窗口应该是正常的，但我没有保存图片
我不知道是个例还是普遍的现象，希望作者知悉

软件很好用，感谢作者！

**Comment by CNOliverZhang** [comment]
感谢您的反馈，已确认问题，将在下一个版本修复。谢谢支持！

l-g-w <notifications@github.com> 于2020年2月22日周六 下午12:04写道：
