### ISSUE TITLE
建议图片拼接能支持png

### ISSUE THREAD

**Issue by GreenChennai** [CNOliverZhang/PotatofieldImageToolkit#11]
如题,我有些图片是透明的如果是jpg就会变白

还有就是我拼接的尺寸都是32X32的
但是转出来之后宽就变成31了,边框啥的我没有选
不知道能不能修复一下?

还有就是软件真的不错这UI也很好看,3Q

**Comment by CNOliverZhang** [comment]
感谢建议！

关于支持PNG的建议，功能上不难实现，但是我本人在开发后的测试中发现了问题，因此发布前去除了。对于尺寸稍大的PNG，其数据量远远超过相同尺寸的JPEG。因此，输出大尺寸PNG文件会造成软件卡死甚至系统死机，从安全方面考量移除了这一功能。当然，不排除随后的版本重新加入这一功能的可能性。

关于尺寸的问题，因为软件在处理拼图前会进行一系列dom操作和尺寸相关的计算，限于Javascript小数精度，可能出现一到两个像素的误差。感谢您反馈这方面的问题，我会寻求解决方案，在未来的某个版本修复。

再次感谢支持！
