### ISSUE TITLE
图片水印处理

### ISSUE THREAD

**Issue by sodading** [CNOliverZhang/PotatofieldImageToolkit#12]
目前文字水印位置单一
我的想法：

- 水印增加透明度
- 铺满整张图片
- 斜着排序

这样可以大幅度增加水印同时不影响正常观看，无奈之举。

**Comment by CNOliverZhang** [comment]
水印可以设置透明度，在选择颜色时可以指定alpha通道，默认为不透明。水印也支持旋转。
