### ISSUE TITLE
图片裁剪工具外围扩充

### ISSUE THREAD

**Issue by cj96248** [CNOliverZhang/PotatofieldImageToolkit#16]
图片裁剪工具中可以显示全部的图片内容，裁剪的时候，不能选择图片外围。 
"拖拽此区域以移动图片"这个视图中，图片以外的位置不能选择。
有两个使用场景：
1. 透明图片可以选择外部区域的话，图片大小就更方便控制；
2. 部分图片，在裁剪的时候，希望外部留白，要是能选择到图片以外的位置就可以实现。

我看网络上也有人提出了类似的需求，在此占个位，希望作者能解决。

**Comment by CNOliverZhang** [comment]
感谢建议，下一版本考虑加入。

Chao <notifications@github.com> 于2020年3月21日周六 下午6:01写道：

**Comment by CNOliverZhang** [comment]
新版本中以加入，请更新后使用。
