### ISSUE TITLE
更新后裁剪工具无法使用+一点小建议

### ISSUE THREAD

**Issue by cat1k** [CNOliverZhang/PotatofieldImageToolkit#17]
（开头依然感谢作者制作的好用工具）
今日使用时发现裁剪工具无法使用，始终显示“即将完成，请稍后”。试过更换图片、裁剪方式、裁剪大小和保存目录都无法成功，昨天使用未更新前是正常的。

一点小建议：因为个人是用这个来替换简陋且很久不更新的“美图秀秀批处理”，功能上这个工具是完败美图秀秀的，但具体使用上各个工具是分开的有一个弊端：如果一张图片需要多个操作，就分别要在每一步都导出一张图，再打开下一步工具去处理，还需要区分最后处理的图片和删除多余图片，很繁琐。是否能计划改进，比如在执行完某一步后选择是导出还是转入其他工具。
这一步涉及到的功能主要是水印、裁剪、尺寸调整、压缩和转换。

感谢。

**Comment by CNOliverZhang** [comment]
感谢反馈！
裁剪工具的bug已确认，目前请使用“批量处理”功能替代，明天将发布新版本解决这一问题。其他建议已纳入参考，在2.0.0版本中将有较大更新。再次感谢支持！

Cat1k <notifications@github.com> 于2020年4月21日周二 上午11:43写道：

**Comment by CNOliverZhang** [comment]
感谢反馈，裁剪工具的bug已确认，明天将推出更新解决这一问题。其他建议已纳入2.0.0版本开发计划。
