### ISSUE TITLE
页面缩放比例和窗口拖放

### ISSUE THREAD

**Issue by 775405984** [CNOliverZhang/PotatofieldImageToolkit#18]
如果将页面缩放比例设置过大，比方说150%或者200%，会导致部分工具窗口显示不全，而即使拖放窗口也会重置，(似乎默认窗口拖放逻辑是必须能够看到窗口标题)，最终导致无法点击下方的操作按钮，甚至连关都关不掉，只能主程序退出。

我觉得有几个解决方法:
1. 更人性化的操作按钮，比如放在标题栏下面。Preferred √√
2. 不限制窗口拖放: 想拖到哪就拖到哪。Preferred √
3. 增加最大化按钮。似乎可行。

@CNOliverZhang

**Comment by 775405984** [comment]
@CNOliverZhang

**Comment by CNOliverZhang** [comment]
感谢反馈，近期将修复界面大小的问题。
