### ISSUE TITLE
BUG: 字体管理只有一个字体

### ISSUE THREAD

**Issue by shao222** [CNOliverZhang/PotatofieldImageToolkit#2]
### 如图所示
---
![image](https://user-images.githubusercontent.com/1249351/74580861-588c9480-4fe3-11ea-8976-959c69438394.png)
![image](https://user-images.githubusercontent.com/1249351/74580867-5fb3a280-4fe3-11ea-871c-d2401a56842b.png)

**Comment by CNOliverZhang** [comment]
软件中只有一种预置字体，其他字体请到“在线字体”中下载。

shao222 <notifications@github.com> 于2020年2月15日周六 上午11:08写道：

**Comment by shao222** [comment]
不好意思 我原以为这个功能可以预览所有系统内字体.
