### ISSUE TITLE
批量添加水印时字体大小和偏移问题

### ISSUE THREAD

**Issue by ttttmr** [CNOliverZhang/PotatofieldImageToolkit#4]
模板设置右，下距离3，字体大小4，应用模板后批量添加（200+张）
部分图片出现水印字体巨大，水印偏移超出图片

正常情况
![hovercard1_watermarked](https://user-images.githubusercontent.com/32825326/74582417-60096900-4ff6-11ea-9a99-c7bf36699222.png)

字体大小正常，但下方超出图片
![response_watermarked](https://user-images.githubusercontent.com/32825326/74582428-9941d900-4ff6-11ea-909b-02e65710c6b2.png)

字体巨大，并超出图片
![dllx86_hex_watermarked](https://user-images.githubusercontent.com/32825326/74582422-79aab080-4ff6-11ea-8049-bc3ee934339a.png)

**Comment by CNOliverZhang** [comment]
感谢反馈！但这个不是bug而是一个feature。

### 关于水印位置偏移的问题
水印在进行定位时，“与上/下/左/右边缘的距离”的单位是“占图片高度/宽度的百分比”，而定位的基准是水印文字的上下基线/左右边缘。即，“下距离设为3”表示，水印文字的字母基线（字母h的下边缘）与图片底部的距离占整张图片高度的3%。因此，对于不同高度的图片，这个距离是不同的，只能保证水印的百分比位置相同。
这种设置方式是基于这样的考量：需要处理的图片的长宽比和尺寸很多时候是不同的，如果以绝对的像素值进行水印定位，对于尺寸差异过大的图片，定位完全无法起到作用。

### 关于水印大小的问题
“水印尺寸”的单位是“占图片宽度的百分比”，因此水印宽度占图片总宽度的百分比是恒定的，而不同宽度的图片水印大小的绝对值是不同的。
考虑的需求是，很多场景下，图片宽度会被统一（例如绝大多数手机版网站和app会让图片宽度占全屏）。以图片宽度的百分比来定义水印尺寸，可以在大多数场景下让水印大小取得一致的视觉效果。

**Comment by ttttmr** [comment]
理解了，但还是有些问题

1. 是用的首字母计算吗，考虑整体下边缘计算嘛

> 水印文字的字母基线（字母h的下边缘）与图片底部的距离占整张图片高度的3%
这样h是满足了，后面的字母j和字母g的下边缘低于字母h，导致超出图片

2. 百分比计算的话对于长图不太友好，视觉效果也不同一

有个想法，可以取宽度百分比，长间距直接等于宽间距，这样看起来应该就没啥问题了

要不注明一下边缘单位吧，以免还有人和我一样理解有误
（或者这两个都提供，用户自己选 像素/百分比

**Comment by CNOliverZhang** [comment]
> 理解了，但还是有些问题
> 
> ## 1. 是用的首字母计算吗，考虑整体下边缘计算嘛
> > 水印文字的字母基线（字母h的下边缘）与图片底部的距离占整张图片高度的3%
> 
> 这样h是满足了，后面的字母j和字母g的下边缘低于字母h，导致超出图片
> 
> ## 2. 百分比计算的话对于长图不太友好，视觉效果也不同一
> 有个想法，可以取宽度百分比，长间距直接等于宽间距，这样看起来应该就没啥问题了
> 
> 另外建议注明一下边缘单位吧，以免还有人和我一样理解有误
> （或者这两个都提供，用户自己选 像素/百分比

基于中文的上下边缘，对应的就是英文的上边缘和基线。例如，“abcdefg”，会截取到“bdf”的上边缘和“abcdef”的下边缘。“g”下方“拖出来”的部分，低于汉字的下边缘，不会计算在内。
