### ISSUE TITLE
感谢及功能建议

### ISSUE THREAD

**Issue by cat1k** [CNOliverZhang/PotatofieldImageToolkit#5]
首先非常非常感谢作者的这款软件。长期以来这些简单的小功能不想开PS就只能靠美图秀秀+美图秀秀批处理来操作，这个软件非常实用且功能强大美观。非常感谢！

使用下来有几点小建议：
1. 主界面能否考虑缩小每一个功能的方框，能在一个界面下显示，方便快速点击打开。
2. 长途拼接加入横向拼接+1。
3. 尺寸调整能否加入固定尺寸（长宽同时固定，不符合尺寸的自动裁剪）。
4. 如果能调整退出到右上角的关闭位置可能更符合使用习惯。

另外一点小疑问：
字体管理我安装的一些小众美化修改的第三方字体无法显示出来，只有系统自带的思源黑。

再次感谢。可以把美图秀秀卸载了…

**Comment by CNOliverZhang** [comment]
> 首先非常非常感谢作者的这款软件。长期以来这些简单的小功能不想开PS就只能靠美图秀秀+美图秀秀批处理来操作，这个软件非常实用且功能强大美观。非常感谢！
> 
> 使用下来有几点小建议：
> 
> 1. 主界面能否考虑缩小每一个功能的方框，能在一个界面下显示，方便快速点击打开。
> 2. 长途拼接加入横向拼接+1。
> 3. 尺寸调整能否加入固定尺寸（长宽同时固定，不符合尺寸的自动裁剪）。
> 4. 如果能调整退出到右上角的关闭位置可能更符合使用习惯。
> 
> 另外一点小疑问：
> 字体管理我安装的一些小众美化修改的第三方字体无法显示出来，只有系统自带的思源黑。
> 
> 再次感谢。可以把美图秀秀卸载了…

感谢建议！
1. 关于界面的建议，我会在未来的开发计划中加入自定义主题，可以横向滚动也可以像你的建议一样平铺工具，敬请期待未来的更新。
2. 横向拼接已在开发计划中。
3. 固定尺寸的建议很有价值，已加入开发计划。
4. 这处修改需要改动的代码较多，修改成本过高，且对使用影响不是很大，暂时不考虑修改。
关于字体管理工具，“本地字体”能管理的只有“本地的”并且是“软件里的”字体，对于系统字体无权限管理。在线字体通过本软件下载也只能用于本软件，但是可以通过浏览器下载安装到系统。每种字体都是官方商用免费，可以随意使用。
再次感谢你的建议！
