### ISSUE TITLE
npm run build提示输入用户名和密码

### ISSUE THREAD

**Issue by qxxz** [CNOliverZhang/PotatofieldImageToolkit#6]
npm run build，到最后时，提示输入用户名和密码。输入后，仍提示这个。

**Comment by CNOliverZhang** [comment]
什么系统？node版本是什么？

qxxz <notifications@github.com> 于 2020年2月17日周一 上午8:22写道：

**Comment by qxxz** [comment]
mac 10.15.3
node v8.9.4
npm 6.13.7
![20200217093814](https://user-images.githubusercontent.com/27119634/74617723-9a474780-5169-11ea-9f4b-b42bb204d21d.jpg)

**Comment by CNOliverZhang** [comment]
可能与权限相关，暂时无法定位问题。当前版本已在CI中测试mac构建通过，下一步将尽快放出mac版本。
