### ISSUE TITLE
富文本制图工具复制粘贴问题

### ISSUE THREAD

**Issue by Blueplanet20120** [CNOliverZhang/PotatofieldImageToolkit#8]
富文本制图工具从wrod里复制过去的内容只显示图片？网页上的可以全部显示！另外建议可以鼠标右键显示粘贴复制剪切功能呀，谢谢！

**Comment by CNOliverZhang** [comment]
富文本制图工具的编辑器部分使用了开源编辑器CKEditor，其本质上是一个可视化html编辑器，因此对word仅能提供有限的支持。而由于本项目基于electron，根据浏览器安全特性，ckeditor不能通过鼠标访问剪贴板。
