### ISSUE TITLE
[功能建议]给图片添加水印建议增加导入图片水印功能...

### ISSUE THREAD

**Issue by wfyihai** [CNOliverZhang/PotatofieldImageToolkit#9]
给图片添加水印建议增加导入图片水印功能，文字建议增加设置透明度与图像叠加模式的功能，这样更方便些。或者可以批量给图片写入元数据。

**Comment by CNOliverZhang** [comment]
文字水印支持设置透明度，设置颜色的地方是rgbs色板，设置颜色的同时可以自定义透明度。添加图片水印功能已加入开发计划。
